title: Jiarui Zhang
description: Technical notes on machine learning systems, theory, and infrastructure.
url: "https://ezoicoder.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: ConventionalMathGFM
  math_engine: mathjax

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      mathjax: true

exclude:
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - test
  - vendor
