title: Jiarui Zhang
description: Personal homepage of Jiarui Zhang.
url: "https://ezoicoder.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: ConventionalMathGFM
  math_engine: mathjax

exclude:
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - test
  - vendor
